"""empty message

Revision ID: 477781362cc1
Revises: 
Create Date: 2024-06-12 15:28:57.169857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477781362cc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Persons',
    sa.Column('pid', sa.Integer(), ),
    sa.Column('name', sa.Text(), ),
    sa.Column('age', sa.Integer(), ),
    sa.Column('city', sa.Text(), ),
    sa.Column('isAdult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Persons')
    # ### end Alembic commands ###
